name: socioeconomics-new
channels:
  - conda-forge
dependencies:
  # R
  - r-base=4.4
  - r-data.table>=1.16.0
  - r-targets
  - r-yaml
  - r-readxl
  - r-countrycode
  - r-testthat
  # geospatial
  - r-terra
  - r-sf
  - r-exactextractr
  # output formats
  - r-ncdf4
  # python
  - python=3.11
  - xarray
  - zarr
  - netcdf4
  - pandas
  - pip
  - pip:
      - pyam-iamc
